### PR TITLE
SlimeVR requires Windows

### PR DESCRIPTION
**Pull request by yaomtc**
SlimeVR currently only works in a Windows environment. I couldn't find any sign they are working on fixing this.
https://docs.slimevr.dev/server-setup/slimevr-setup.html

Vive Trackers (as well as additional controllers, technically) are the only way to get more tracking on Linux at the moment.

### CODE REVIEW

**Comment by AuroraNemoia** [comment]
SlimeVR is Java-based. It does not currently work on Linux no. But the only real obstacle to overcome is interprocess communication between the server and the SteamVR driver. Which currently uses Windows mailboxes.

Slime has very real potential to run on other platforms. Kinect does not, I checked and making the kind of libfreenect to Wine compatibility layer is simply not feasible with the architecture of Microsoft's SDK.

Rewording the paragraph to make that clear would be a more sensible solution than removing it.

**Comment by yaomtc** [comment]
Fixed, how's that? I could make that text a link [to this](https://github.com/SlimeVR/SlimeVR-OpenVR-Driver/issues/2) but maybe that's unnecessary

**Comment by AuroraNemoia** [comment]
Making "support is planned" into a link to that issue would make sense yeah. I would edit it. But I'm an idiot when it comes to Git and have no idea how to pile commits inside of a merge request. (I'm not the one developing the app as you might be able to tell.)

**Comment by yaomtc** [comment]
Done!

**Pull request merged**
